#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD3657D24D058434C (petri@digip.org)
#
Name     : jansson
Version  : 2.12
Release  : 5
URL      : http://www.digip.org/jansson/releases/jansson-2.12.tar.gz
Source0  : http://www.digip.org/jansson/releases/jansson-2.12.tar.gz
Source1  : http://www.digip.org/jansson/releases/jansson-2.12.tar.gz.asc
Summary  : Library for encoding, decoding and manipulating JSON data
Group    : Development/Tools
License  : MIT
Requires: jansson-lib = %{version}-%{release}
Requires: jansson-license = %{version}-%{release}

%description
To build the documentation, invoke
make html
Then point your browser to _build/html/index.html.

%package dev
Summary: dev components for the jansson package.
Group: Development
Requires: jansson-lib = %{version}-%{release}
Provides: jansson-devel = %{version}-%{release}
Requires: jansson = %{version}-%{release}

%description dev
dev components for the jansson package.


%package lib
Summary: lib components for the jansson package.
Group: Libraries
Requires: jansson-license = %{version}-%{release}

%description lib
lib components for the jansson package.


%package license
Summary: license components for the jansson package.
Group: Default

%description license
license components for the jansson package.


%prep
%setup -q -n jansson-2.12
cd %{_builddir}/jansson-2.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604098061
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604098061
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jansson
cp %{_builddir}/jansson-2.12/LICENSE %{buildroot}/usr/share/package-licenses/jansson/04734befe9a48b09072cbdfaa17a0c5d98d67f56
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/jansson.h
/usr/include/jansson_config.h
/usr/lib64/libjansson.so
/usr/lib64/pkgconfig/jansson.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libjansson.so.4
/usr/lib64/libjansson.so.4.11.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jansson/04734befe9a48b09072cbdfaa17a0c5d98d67f56
